### ISSUE TITLE
Fecharam meu PR

### ISSUE THREAD

**Issue by Mario-aj** [tech-pro-bem/teste-frontend#35]
Saudações!

Assim, eu não sei quem fechou o meu, mas provavelmente é alguém da vossa equipe. Eu achei isso bem ruim para falar verdade. Eu dediquei meu tempo fazendo o desafio para vocês simplesmente fecharem sem  nenhum comentário,

**Comment by lucas-lm** [comment]
Olá, @Mario-aj !

Não consegui identificar como seu PR foi fechado (veja que não aparece nenhum nome).

![image](https://user-images.githubusercontent.com/29049644/177430623-e6d710f3-3c37-4318-a331-26a73c0dc92a.png)

Mas não se preocupe, já reabri seu PR e estamos avaliando todas as entregas. Logo mais estaremos olhando a sua e entrando em contato com todos, ok? 

Não deixaremos de olhar nenhum pull request que tenha sido aberto durante o período de inscrição, independente do status :)
